services:
  gateway:
    image: nginx:latest
    container_name: gateway_service
    volumes:
      - ./services/gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - auth-network

  auth:
    build:
      context: ./services/auth
    container_name: auth_service
    volumes:
      - ./secrets/tapago-admin.json:/app/secrets/firebase-admin.json
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/secrets/firebase-admin.json
      - PORT=3000
    networks:
      - auth-network

  customers:
    build:
      context: ./services/customers
    container_name: customers_service
    volumes:
      - ./secrets/tapago-admin.json:/app/secrets/firebase-admin.json
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/secrets/firebase-admin.json
      - PORT=3000
    networks:
      - auth-network

  users:
    build:
      context: ./services/users
    container_name: users_service
    volumes:
      - ./secrets/tapago-admin.json:/app/secrets/firebase-admin.json
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/secrets/firebase-admin.json
      - PORT=3000
    networks:
      - auth-network

  transactions:
    build:
      context: ./services/transactions
    container_name: transactions_service
    volumes:
      - ./secrets/tapago-admin.json:/app/secrets/firebase-admin.json
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/secrets/firebase-admin.json
      - PORT=3000
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge
