version: "3.8"

services:
  auth:
    build:
      context: ./services/auth
    container_name: auth_service
    ports:
      - "5000:3000"
    environment:
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - auth-network

  customers:
    build:
      context: ./services/customers
    container_name: customers_service
    ports:
      - "5001:3000"
    environment:
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge
